apiVersion: apps/v1
kind: Deployment
metadata:
  name: postal-code-app
  labels:
    app: postal-code
spec:
  replicas: 4
  selector:
    matchLabels:
      app: postal-code
  template:
    metadata:
      labels:
        app: postal-code
    spec:
      containers:
        - name: postal-code-app
          image: ssumura/postal-code@sha256:9a59e8606c57b3066170b6bfa63f91eba091430df4c2b820159df0a1ddfee94a
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
